### PR TITLE
Fix for #1458

### LINKED ISSUE #1458: Bug: Syncing events to the database may cause incomplete data on the server
There is a race condition when inserting new `Event`s into the datastore which may cause incomplete events to be uploaded to the server. This happens because in `ExperimentProviderUtil`'s `insertEvent()` method, all responses are inserted separately into the DB (by calling the `insertResponse()` method for every response in the event).

In meantime, the `SyncService` may start syncing data to the server, reconstructing `Event`s from the database by calling a.o. `ExperimentProviderUtil`'s `findResponsesFor(Event)` method. If `insertEvent()` is not done storing the responses yet, this may yield an incomplete `Event` object to be reconstructed, and sent to the server. As soon as the `SyncService` completed sending this Event object to the server, it will update the database to state this `Event` was uploaded, causing the responses inserted later to never be uploaded to the server.

I suggest solving this by making the `insertEvent()` method an atomic operation as far as the `findResponsesFor()` method is concerned, by creating a shared mutex. A more complete solution would probably be to have mutexes (or better yet, transactions) for all database code that handles multiple inserts/queries as part of one operation.

### PR DESCRIPTION
**Pull request by BramBonne**
This pull request fixes a race condition when performing concurrent read/writes on Paco's DB (fixes #1458 )

### CODE REVIEW

File: Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java [hunk 1]
```diff
@@ -738,14 +745,23 @@ public void loadEventsForExperiment(Experiment experiment) {
...
+      long rowId = Long.parseLong(uri.getLastPathSegment());
+      event.setId(rowId);
+      for (Output response : event.getResponses()) {
+        response.setEventId(rowId);
+        insertResponse(response);
+      }
+      writeLock.unlock();
+      return uri;
+    } catch (Exception e) {
+      writeLock.unlock();
```
Comment (BobEvans) [inline Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java]: Unlock should be done in a finally block so that it always gets called.

File: Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java [hunk 2]
```diff
@@ -886,6 +906,7 @@ private Event findEventBy(String select, String[] selectionArgs, String sortOrde
       if (cursor != null) {
         cursor.close();
       }
+      readLock.unlock();
```
Comment (BobEvans) [inline Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java]: unlock in a finally block

File: Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java [hunk 3]
```diff
@@ -869,12 +885,16 @@ private Event findEventBy(String select, String[] selectionArgs, String sortOrde
   private List<Output> findResponsesFor(Event event) {
```
Comment (BobEvans) [inline Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java]: This is too granular a place for the lock. It should lock around all insertEvent and find/getEvent calls instead of at the level of the responses.

Any method that uses a contentResolver to get at EventColumns.CONTENT_URI needs to have the appropriate lock to keep the event table coherent.

**Comment by BramBonne** [comment]
Thanks for the comments! I'll update my code accordingly.

File: Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java (hunk 2 above)
Comment (BramBonne) [inline Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java]: I'm not sure I understand what you mean: should the `unlock()` not happen in the `finally{}` block here?
In the new commit, this code is scrapped in favor of having locks in the `insert/findEvent()` methods, but the `unlock()`s happen in the `finally{}` blocks there too. Let me know if you want me to change that.

Comment (BobEvans) [inline Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java]: Hi Bram,

Sorry for the confusion. 

When I look at the latest pull request, it looks like the unlock events are in the normal flow (not in finally blocks). Am I looking at the right pull request?

Best,
Bob

Http://www.pacoapp.com/

File: Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java [hunk 4]
```diff
@@ -838,13 +858,15 @@ private Event findEventBy(String select, String[] selectionArgs, String sortOrde
       if (cursor != null) {
         cursor.close();
       }
+      eventStorageReadLock.unlock();
```
Comment (BobEvans) [inline Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java]: wrap in finally block

File: Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java [hunk 5]
```diff
@@ -862,6 +884,7 @@ private Event findEventBy(String select, String[] selectionArgs, String sortOrde
...
```
Comment (BobEvans) [inline Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java]: finally

File: Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java [hunk 6]
```diff
@@ -1387,6 +1419,7 @@ public void loadLastEventForExperiment(Experiment experiment) {
...
```
Comment (BobEvans) [inline Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java]: finally

File: Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java [hunk 7]
```diff
@@ -1563,6 +1597,7 @@ public void loadEventsForExperimentGroup(Experiment experiment, ExperimentGroup
...
```
Comment (BobEvans) [inline Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java]: finally

File: Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java (hunk 2 above)
Comment (BobEvans) [inline Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java]: Ah! I see it now. The github diff viewer was eliding the finally block lines.

Looks good.

Bob

Http://www.pacoapp.com/

**Comment by BramBonne** [comment]
Yay! Thanks :-)
